### ISSUE TITLE
configure() crashing my Android emulator

### ISSUE THREAD

**Issue by MartinCura** [superwall/react-native-superwall#24]
Hi there! 👋🏼

First time using Superwall, and i've been having a problem: a couple of seconds after running `Superwall.configure(...)` my Android emulator suddenly crashes completely, without any explanation and i can't find the reason.

I'm using the latest version `1.3.5` which i'm testing after bumping from `1.3.2`.

The Android in my phone doesn't have the issue, nor do the iOS simulators/devices of my colleagues. I'm also at a loss of how to even troubleshoot this. I've tried setting the `options.logging.level = superwall.LogLevel.Debug` to no avail.

Any ideas? Anything i may be missing? Thank you!

**Comment by MartinCura** [comment]
Small update. Running the emulator from the commandline i get to see there's a segmentation fault somehow:

```
λ martin ~ → DEBUG=1 emulator -avd Pixel_8_API_35 -verbose

(...)

DEBUG   | getMultiDisplay 0 x 0 y 0 w 1080 h 2400 dpi 420 flag 0 enable 1
DEBUG   | successfully created cuda video decoder for HEVC, with gpu texture mode on
[1]    3258796 segmentation fault (core dumped)  DEBUG=1 emulator -avd Pixel_8_API_35 -verbose
```

The segfault seemed to happen right after the previous 2 lines.

As a clarification, if i comment out the `Superwall.configure(...)` line, i never get this crash.

**Comment by ianrumac** [comment]
Hey @MartinCura !

That's quite weird, we haven't encountered this issue yet 🤔 
A few questions that might help investigate:
* Did it also happen with 1.3.2 or just started with 1.3.5?
* Does it happen only on a specific emulator or all of them? If specific, could you send more details about it?
* Could you try [disabling preloading](https://superwall.com/docs/using-superwalloptions#preloading-paywalls)? I have a suspicion it might be some kind of a chromium crash that's causing it.

**Comment by MartinCura** [comment]
Hey, thanks for the quick reply!

- It happens in both versions, didn't try older ones.
- I'm only trying this in the Android emulator, the AVD is a Pixel_8_API_35; i also tried passing `-gpu swiftshaedr_indirect` (and maybe `-gpu angle_indirect`), which are CPU-based graphics iiuc, and they do not crash. I did upgrade my GPU drivers and all other system packages but still crashes for `-gpu host`.
- **This stopped it from crashing!** Do i have to make any other changes for using this normally?

**Comment by ianrumac** [comment]
Hey Martin!
Just wanted to keep you updated on the issue - in the Android SDK we released a version with webview recovery in cases of chromium crash. We'll be pushing this to our RN SDK shortly!

**Comment by MartinCura** [comment]
> Hey Martin!
> Just wanted to keep you updated on the issue - in the Android SDK we released a version with webview recovery in cases of chromium crash. We'll be pushing this to our RN SDK shortly!

Just saw this, awesome! Would it be best for us to reenable preloading? I don't remember if it's important. (Happy holidays!)

**Comment by ianrumac** [comment]
Hey Martin!
That really depends on your app/usecase - but I would say mostly yes, since any such chromium crash will be caught and the webview recreated in the latest versions!

**Comment by MartinCura** [comment]
Tried with the latest version and my Android emulator still crashed 😅 so i'm leaving the preloading off.
